# Generated by Django 4.1.4 on 2022-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=40, verbose_name='Фирма')),
                ('qty', models.CharField(blank=True, max_length=40, verbose_name='Шт.')),
                ('file_name', models.CharField(blank=True, max_length=65, null=True, verbose_name='Название')),
                ('plate_size', models.CharField(blank=True, max_length=40, verbose_name='Размер')),
                ('equipment', models.CharField(blank=True, choices=[('BLUE', 'Синяя'), ('GREEN', 'Зелёная'), ('AURORA', 'Аврора B0'), ('THERMAL', 'Термальная'), ('FIRST', 'Первая')], max_length=40, verbose_name='Машина')),
                ('add_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('punch', models.CharField(blank=True, choices=[('PUNCH', 'Панч'), ('PUNCH_BEND', 'Панч+Загиб')], max_length=255, verbose_name='Панч')),
                ('stage', models.CharField(choices=[('UNREADY', 'На машине'), ('READY', 'Готов')], default='На машине', max_length=255, verbose_name='Состояние')),
                ('operator', models.CharField(blank=True, choices=[('YURA', 'Юрий'), ('ZIYO', 'Зийо'), ('AZIZ', 'Азиз'), ('DIMA', 'Дмитрий'), ('ANDREY', 'Андрей'), ('OLEG', 'Олег')], max_length=255, verbose_name='Вывел')),
                ('ready_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Время готовности')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
