# Generated by Django 4.1.4 on 2022-12-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_from_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(blank=True, max_length=65, null=True, unique_for_date=True, verbose_name='Название'),
        ),
    ]
