# Generated by Django 4.1.4 on 2022-12-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_from_db', '0002_alter_files_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Название'),
        ),
    ]
