# Generated by Django 4.1.4 on 2023-01-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_from_db', '0003_alter_files_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='equipment',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('BLUE', 'Синяя'), ('GREEN', 'Зелёная'), ('AURORA', 'Аврора B0'), ('THERMAL', 'Термальная'), ('FIRST', 'Первая')], max_length=40, verbose_name='Машина'),
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('company_name', 'qty', 'file_name', 'plate_size', 'add_date_time')},
        ),
    ]
