# Generated by Django 4.1.4 on 2023-01-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_from_db', '0004_alter_files_equipment_alter_files_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='equipment',
            field=models.CharField(blank=True, choices=[('BLUE', 'Синяя'), ('GREEN', 'Зелёная'), ('AURORA', 'Аврора B0'), ('THERMAL', 'Термальная'), ('FIRST', 'Первая')], max_length=40, verbose_name='Машина'),
        ),
    ]
